### PR TITLE
Add thread support

### PR DESCRIPTION
**Pull request by sgedward**
#55
 
Change:
slack_comm.py

### CODE REVIEW

**Comment by mikegrima** [comment]
Hello @sgedward. Would prefer not making use of `global`s.  

I think this would be best accomplished by having a function to return a timestamp, and having `thread` sent in via a keyword arg to the `say*` functions.

I think an approach similar to #63 would best implement this feature.

**Comment by sgedward** [comment]
@mikegrima  thanks for leting me know. fixed

**Comment by mikegrima** [comment]
Testing this today

**Comment by mikegrima** [comment]
@sgedward slight merge conflict that should be very easy to fix.

**Comment by mikegrima** [comment]
I'll fix the conflict -- some changes I need to make to incorporate this PR with the ephemeral messages one.

**Pull request merged**
