### PR TITLE
Remove the github plugin dependency to start bot

### PR DESCRIPTION
**Pull request by goduncan**
* This change moves the github plugin to the `command_plugin` directory allowing the bot to be run with only a Slack Token.
* Idea is to use hubcommander as generic python Slack bot framework for people to build on.

### CODE REVIEW

**Comment by mikegrima** [comment]
I'll try to take a look at this later this week.

**Comment by mikegrima** [comment]
I'll need to see how this works with regards to plugins that make use of GitHub.

For example, I'll need to see how the TravisCI plugin would work with this change.

**Comment by mikegrima** [comment]
@goduncan : Been busy lately -- didn't forget about this.  Can you resolve the conflicts?

**Comment by goduncan** [comment]
No worries. I haven't had time to test if the Travis plugin works as before with the changed but the bot starts with it enabled.

**Comment by goduncan** [comment]
Hello. Do you still think it's likely that you will be merge this?

**Comment by mikegrima** [comment]
Hi @goduncan ! I will look at it today. **I PROMISE!**

**Comment by mikegrima** [comment]
You will need to make a change here: https://github.com/goduncan/hubcommander/blob/develop/command_plugins/travis_ci/plugin.py#L72

GitHub is a dependency for Travis CI.

**Comment by mikegrima** [comment]
@goduncan The PR looks good.

I will submit a follow-up PR with the additional fixes for Travis CI.

**Pull request merged**
